// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(BoligmappaDbContext))]
    [Migration("20260505075226_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("Infrastructure.Persistence.DAOs.DocumentDao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpiryDate");

                    b.HasIndex("PropertyId");

                    b.ToTable("Documents", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Persistence.DAOs.PropertyDao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Properties", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Persistence.DAOs.ReminderSnoozeDao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SnoozedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("SnoozedUntil")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId")
                        .IsUnique();

                    b.HasIndex("SnoozedUntil");

                    b.ToTable("ReminderSnoozes", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Persistence.DAOs.DocumentDao", b =>
                {
                    b.HasOne("Infrastructure.Persistence.DAOs.PropertyDao", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("Infrastructure.Persistence.DAOs.ReminderSnoozeDao", b =>
                {
                    b.HasOne("Infrastructure.Persistence.DAOs.DocumentDao", "Document")
                        .WithOne("ReminderSnooze")
                        .HasForeignKey("Infrastructure.Persistence.DAOs.ReminderSnoozeDao", "DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("Infrastructure.Persistence.DAOs.DocumentDao", b =>
                {
                    b.Navigation("ReminderSnooze");
                });
#pragma warning restore 612, 618
        }
    }
}
